### ISSUE TITLE
添加实体时报“TypeError: FlowHandler.async_create_entry() missing 1 required keyword-only argument: 'title'"

### ISSUE THREAD

**Issue by ctian282** [larry-wong/bemfa#25]
使用最新1.1.0，报unknown error 貌似错误是`File "/config/custom_components/bemfa/config_flow.py", line 150, in async_step_entities
return self.async_create_entry(
TypeError: FlowHandler.async_create_entry() missing 1 required keyword-only argument: 'title'`

完整日志错误信息如下

```
2023-01-28 10:05:23.460 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/bemfa/config_flow.py", line 150, in async_step_entities
return self.async_create_entry(
TypeError: FlowHandler.async_create_entry() missing 1 required keyword-only argument: 'title'
```

**Comment by larry-wong** [comment]
v1.1.1 版本修复了此问题。
