### ISSUE TITLE
配置失败，日志如下，烦请看下

### ISSUE THREAD

**Issue by hekalong** [larry-wong/bemfa#29]
Logger: aiohttp.server
Source: custom_components/bemfa/config_flow.py:282
Integration: Bemfa ([documentation](https://github.com/larry-wong/bemfa), [issues](https://github.com/larry-wong/bemfa/issues))
First occurred: 02:45:42 (4 occurrences)
Last logged: 02:58:53

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 267, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/bemfa/config_flow.py", line 120, in async_step_create_sync
    service = self._get_service()
  File "/config/custom_components/bemfa/config_flow.py", line 282, in _get_service
    return self.hass.data[DOMAIN].get(self._entry_id)["service"]
TypeError: 'NoneType' object is not subscriptable

**Comment by hekalong** [comment]
看了其他人的问题，回复说是“昨天是这样，集成那重载一下，今天已经恢复正常了。”
4.8日重载了以下  好了。可能前几天有问题把。

**Comment by larry-wong** [comment]
v1.3.2 版本已经修复重连失败的问题。
