### ISSUE TITLE
配置密钥后无法链接

### ISSUE THREAD

**Issue by y306702588** [larry-wong/bemfa#30]
Home Assistant 2023.3.5
Supervisor 2023.04.0
Operating System 9.5
前端版本： 20230309.1 - latest

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bemfa/__init__.py", line 31, in async_setup_entry
    await service.async_start(
  File "/config/custom_components/bemfa/service.py", line 37, in async_start
    self._bemfa_mqtt.connect()
  File "/config/custom_components/bemfa/mqtt.py", line 79, in connect
    self._mqttc.connect(MQTT_HOST, MQTT_PORT, MQTT_KEEPALIVE)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by larry-wong** [comment]
v1.3.2 版本已经修复重连失败的问题。
