### ISSUE TITLE
设置失败

### ISSUE THREAD

**Issue by 1761057841** [larry-wong/bemfa#31]
Ha版本2023.4.0
删除实体直接显示错误求大老帮忙看看
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/bemfa/mqtt.py:79
Integration: Bemfa (documentation, issues)
First occurred: 下午3:06:34 (1 occurrences)
Last logged: 下午3:06:34

Error setting up entry for bemfa
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bemfa/__init__.py", line 31, in async_setup_entry
    await service.async_start(
  File "/config/custom_components/bemfa/service.py", line 37, in async_start
    self._bemfa_mqtt.connect()
  File "/config/custom_components/bemfa/mqtt.py", line 79, in connect
    self._mqttc.connect(MQTT_HOST, MQTT_PORT, MQTT_KEEPALIVE)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by qfwc258** [comment]
同样的问题，求解。

**Comment by monkeychou** [comment]
一样。应该是都出问题了。我删了重新添加也不行

**Comment by 1761057841** [comment]
我的Supervisor也出问题了一直显示设置失败

**Comment by ptaoo** [comment]
一样问题。2023-04-06 21:17:36.967 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bemfa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-06 21:18:25.152 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for bemfa
File "/config/custom_components/bemfa/__init__.py", line 31, in async_setup_entry
File "/config/custom_components/bemfa/service.py", line 37, in async_start
self._bemfa_mqtt.connect()
File "/config/custom_components/bemfa/mqtt.py", line 79, in connect
2023-04-06 21:18:33.102 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for bemfa
File "/config/custom_components/bemfa/__init__.py", line 31, in async_setup_entry
File "/config/custom_components/bemfa/service.py", line 37, in async_start
self._bemfa_mqtt.connect()
File "/config/custom_components/bemfa/mqtt.py", line 79, in connect
File "/config/custom_components/bemfa/config_flow.py", line 120, in async_step_create_sync
File "/config/custom_components/bemfa/config_flow.py", line 282, in _get_service
File "/config/custom_components/bemfa/config_flow.py", line 153, in async_step_modify_sync
File "/config/custom_components/bemfa/config_flow.py", line 282, in _get_service

**Comment by shgqynet2** [comment]
昨天是这样，集成那重载一下，今天已经恢复正常了。

**Comment by larry-wong** [comment]
v1.3.2 版本已经修复重连失败的问题。
